name=Inkplate LVGL Library
version=1.1.0
author=Soldered <hello@soldered.com>
maintainer=Josip Šimun Kuči <josip@soldered.com>
sentence=Inkplate boards driver library
paragraph=Implements the LVGL library on the Inkplate family of products
category=Display
url=https://github.com/SolderedElectronics/Inkplate-LVGL-Library/tree/main
architectures=*
includes=Inkplate-LVGL.h
repository=https://github.com/SolderedElectronics/Inkplate-LVGL-Library/tree/main